apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: todo
    app_type: cache
spec:
  clusterIP: None
  ports:
  - port: 7000
    targetPort: 6379
    name: redis
  selector:
    app: todo
    app_type: cache