apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
  labels:
    app_type: api
    app: todo-api
spec:
  selector:
    matchLabels:
      app: todo-api
  replicas: 2 # tells deployment to run 1 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app_type: api
        app: todo-api
    spec:
      containers:
      - name: todo-server
        image: lsampras/todo_api_server:v3
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: server-config
        ports:
        - containerPort: 3030
---
apiVersion: v1
kind: Service
metadata:
  name: todo-api-service
  labels:
    app_type: api
    app: todo-api
spec:
  type: NodePort
  ports:
  - port: 3030
    protocol: TCP
    targetPort: 3030
  selector:
    app: todo-api
