# Creating a storage class & volumes for Postgres & Redis
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
reclaimPolicy: Delete

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-retained-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true

---
# Enable this if using non-helm based redis
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: local-pv1
#   labels:
#     app_type: cache
# spec:
#   storageClassName: local-storage
#   capacity:
#     storage: 1Gi
#   accessModes:
#     - ReadWriteOnce
#   persistentVolumeReclaimPolicy: Delete
#   hostPath:
#     path: "/storage/data1"

# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: local-pv2
#   labels:
#     app_type: cache
# spec:
#   storageClassName: local-storage
#   capacity:
#     storage: 1Gi
#   accessModes:
#     - ReadWriteOnce
#   persistentVolumeReclaimPolicy: Delete
#   hostPath:
#     path: "/storage/data2"

# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: local-pv3
#   labels:
#     app_type: cache
# spec:
#   storageClassName: local-storage
#   capacity:
#     storage: 1Gi
#   accessModes:
#     - ReadWriteOnce
#   persistentVolumeReclaimPolicy: Delete
#   hostPath:
#     path: "/storage/data3"

# ---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv4
  labels:
    app_type: db
spec:
  storageClassName: local-retained-storage
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/storage/data4"

---
# kind: PersistentVolumeClaim
# apiVersion: v1
# metadata:
#   name: postgres-pv-claim
#   labels:
#     app: todo
#     app_type: db
# spec:
#   storageClassName: "local-retained-storage"
#   selector:
#     matchLabels:
#       app_type: db
#   capacity:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 2Gi