apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  labels:
    app_type: db
    app: todo
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
        app_type: db
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        envFrom:
        - configMapRef:
            name: postgres-configuration
        ports:
        - containerPort: 5432
          name: postgresdb
        volumeMounts:
        - name: pv-data
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: pv-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "local-retained-storage"
      selector:
        matchLabels:
          app_type: db
      resources:
        requests:
          storage: 2Gi