apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    app: todo
    app_type: db
spec:
  ports:
  - port: 5432
    name: postgres
  type: NodePort 
  selector:
    app: postgres